<?php return array(
    'root' => array(
        'name' => 'ffw/wordpress-theme',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'be5aead8dea0ebb5960f899f197862ad401205f9',
        'type' => 'wordpress-theme',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'erusev/parsedown' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '96baaad00f71ba04d76e45b4620f54d3beabd6f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ffw/wordpress-theme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'be5aead8dea0ebb5960f899f197862ad401205f9',
            'type' => 'wordpress-theme',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yahnis-elsts/plugin-update-checker' => array(
            'pretty_version' => 'v5.6',
            'version' => '5.6.0.0',
            'reference' => 'a2db6871deec989a74e1f90fafc6d58ae526a879',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/plugin-update-checker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
