<?php return array(
    'root' => array(
        'name' => 'ffw/wordpress-theme',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '7e5947e4eee7d72744c189da253b68f67ec82276',
        'type' => 'wordpress-theme',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'erusev/parsedown' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '96baaad00f71ba04d76e45b4620f54d3beabd6f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ffw/wordpress-theme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '7e5947e4eee7d72744c189da253b68f67ec82276',
            'type' => 'wordpress-theme',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yahnis-elsts/plugin-update-checker' => array(
            'pretty_version' => 'v5.7',
            'version' => '5.7.0.0',
            'reference' => '275a96a2a18d03c34c87f35cb68673c8c49ac3b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/plugin-update-checker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
